In [2]:
import duckdb

In [2]:
df =duckdb.query("""
    SELECT *
    FROM 
   'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv'
""").df()

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
# EDA()
import duckdb
df= duckdb.query("""
SELECT *
FROM 
'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'            
""").df()

df.head()

   total_bill   tip     sex  smoker  day    time  size
0       16.99  1.01  Female   False  Sun  Dinner     2
1       10.34  1.66    Male   False  Sun  Dinner     3
2       21.01  3.50    Male   False  Sun  Dinner     3
3       23.68  3.31    Male   False  Sun  Dinner     2
4       24.59  3.61  Female   False  Sun  Dinner     4

In [4]:
#EDA
duckdb.query("""
SELECT 
day,
AVG(total_bill) AS avg_bill
FROM df
GROUP BY day
""").df()

    day   avg_bill
0   Fri  17.151579
1  Thur  17.682742
2   Sat  20.441379
3   Sun  21.410000

In [ ]:
# feature engineering 
#features = duckdb.query...

In [5]:
X=df['total_bill']
y=df['tip']

In [6]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [7]:
X

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [9]:
#bad way
#SELECT *
#FROM 's3//my-bucket.parquet';

In [12]:
duckdb.query('SELECT 1')

┌───────┐
│   1   │
│ int32 │
├───────┤
│     1 │
└───────┘

In [14]:
#ATTACH 'my_analysis.db' AS my_db;
#USE my_db;

In [15]:
import duckdb
# connect to a persistent file 
conn = duckdb.connect("unisole.db")

In [18]:
conn.execute("""
CREATE TABLE  unisole_sample AS 
SELECT * 
FROM 
'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'
LIMIT 100
""")

CatalogException: Catalog Error: Table with name "unisole_sample" already exists!

In [19]:
result= conn.execute("SELECT COUNT(*) FROM  unisole_sample").fetchall()
print(result)

[(244,)]